environment: PolyCityScene # 'PolyCityScene, PennovationScene, ForestScene, FloodedGroundsScene'

quadrotor:
  startPosition:
    x: 0.0
    y: 0.0
    z: 0.0
  startOrientation:
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

ugv:
  startPosition:
    x: 0.0
    y: 0.0
    z: 1.0
  startOrientation:
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
